android.useAndroidX=true
org.gradle.jvmargs=-Xmx2048m
systemProp.http.proxyHost=21.0.0.111
systemProp.http.proxyPort=15004
systemProp.http.proxyUser=container_container_01E9epDuBHbfxiT4oUyjQH3P--claude_code_remote--45f190
systemProp.http.proxyPassword=jwt_eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiIsImtpZCI6Iks3dlRfYUVsdXIySGdsYVJ0QWJ0UThDWDU4dFFqODZIRjJlX1VsSzZkNEEifQ.eyJpc3MiOiJhbnRocm9waWMtZWdyZXNzLWNvbnRyb2wiLCJvcmdhbml6YXRpb25fdXVpZCI6ImEzYjc2YjAzLWQxNTEtNGJkYi1hOWNjLThkOTUzOTk4MjVkYSIsImlhdCI6MTc3MjMyMDEwMywiZXhwIjoxNzcyMzM0NTAzLCJhbGxvd2VkX2hvc3RzIjoiKiIsImlzX2hpcGFhX3JlZ3VsYXRlZCI6ImZhbHNlIiwiaXNfYW50X2hpcGkiOiJmYWxzZSIsInVzZV9lZ3Jlc3NfZ2F0ZXdheSI6InRydWUiLCJzZXNzaW9uX2lkIjoic2Vzc2lvbl8wMTVhWUJ4YTU3SGZBR2lBeVJZMjJIZGUiLCJjb250YWluZXJfaWQiOiJjb250YWluZXJfMDFFOWVwRHVCSGJmeGlUNG9VeWpRSDNQLS1jbGF1ZGVfY29kZV9yZW1vdGUtLTQ1ZjE5MCJ9.Y1--PAQrmXnIeJZrfBNwwnBgKygcWIICz7DCWH5qXiGw1Ht6ehrHev0gqMzneqpCjv_vX5Jo6yIuS9Tsqt5oqg
systemProp.https.proxyHost=21.0.0.111
systemProp.https.proxyPort=15004
systemProp.https.proxyUser=container_container_01E9epDuBHbfxiT4oUyjQH3P--claude_code_remote--45f190
systemProp.https.proxyPassword=jwt_eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiIsImtpZCI6Iks3dlRfYUVsdXIySGdsYVJ0QWJ0UThDWDU4dFFqODZIRjJlX1VsSzZkNEEifQ.eyJpc3MiOiJhbnRocm9waWMtZWdyZXNzLWNvbnRyb2wiLCJvcmdhbml6YXRpb25fdXVpZCI6ImEzYjc2YjAzLWQxNTEtNGJkYi1hOWNjLThkOTUzOTk4MjVkYSIsImlhdCI6MTc3MjMyMDEwMywiZXhwIjoxNzcyMzM0NTAzLCJhbGxvd2VkX2hvc3RzIjoiKiIsImlzX2hpcGFhX3JlZ3VsYXRlZCI6ImZhbHNlIiwiaXNfYW50X2hpcGkiOiJmYWxzZSIsInVzZV9lZ3Jlc3NfZ2F0ZXdheSI6InRydWUiLCJzZXNzaW9uX2lkIjoic2Vzc2lvbl8wMTVhWUJ4YTU3SGZBR2lBeVJZMjJIZGUiLCJjb250YWluZXJfaWQiOiJjb250YWluZXJfMDFFOWVwRHVCSGJmeGlUNG9VeWpRSDNQLS1jbGF1ZGVfY29kZV9yZW1vdGUtLTQ1ZjE5MCJ9.Y1--PAQrmXnIeJZrfBNwwnBgKygcWIICz7DCWH5qXiGw1Ht6ehrHev0gqMzneqpCjv_vX5Jo6yIuS9Tsqt5oqg
systemProp.http.nonProxyHosts=localhost|127.0.0.1
